In [1]:
import pandas as pd
import numpy as np
from sklearn.semi_supervised import LabelSpreading
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('text_embs.csv')

In [3]:
df.head(5)

,id,article_text,e1,e2,e3,e4,e5
0,0,Spin me round: Conceptual image of the distant...,-22.158750,0.724839,0.288074,-4.338476,-78.955190
1,1,Euclid mission releases its first images\nThe ...,-69.417400,35.862324,-0.087313,-4.319662,71.955670
2,2,"This colourful stripe of stars, gas, and dust ...",-19.161320,16.865223,0.275305,-4.339422,-95.052050
3,3,Scientists say they are stunned after discover...,39.257393,-0.624030,-0.312458,-3.406152,15.344043
4,4,Just a few swabs from a handful of leaves can ...,77.716700,-10.334601,-0.358630,-3.616157,35.430443

Ручная разметка

In [4]:
df['target'] = -1

0 - космос, 1 - биология

In [5]:
df.loc[1, 'target'] = 0

In [6]:
df.loc[10, 'target'] = 0

In [7]:
df.loc[4, 'target'] = 1

In [8]:
df.loc[7, 'target'] = 1

In [9]:
df.head(11)

,id,article_text,e1,e2,e3,e4,e5,target
0,0,Spin me round: Conceptual image of the distant...,-22.158750,0.724839,0.288074,-4.338476,-78.955190,-1
1,1,Euclid mission releases its first images\nThe ...,-69.417400,35.862324,-0.087313,-4.319662,71.955670,0
2,2,"This colourful stripe of stars, gas, and dust ...",-19.161320,16.865223,0.275305,-4.339422,-95.052050,-1
3,3,Scientists say they are stunned after discover...,39.257393,-0.624030,-0.312458,-3.406152,15.344043,-1
4,4,Just a few swabs from a handful of leaves can ...,77.716700,-10.334601,-0.358630,-3.616157,35.430443,1
5,5,"Standing on the marina, Rob Skelly peers into ...",25.035158,38.126000,-0.535336,-3.778501,-75.229970,-1
6,6,The James Webb space telescope has detected wh...,21.771069,-16.705242,0.035637,-4.280477,135.175920,-1
7,7,We all know how important sleep is for mental ...,31.504581,37.482710,0.424354,-3.447748,-138.741090,1
8,8,"In a former gold mine a mile underground, insi...",-6.323969,-16.945358,-0.056686,-4.229829,112.954500,-1
9,9,Molecular scale structure and kinetics of laye...,34.213360,35.360607,0.041953,-3.384598,-7.783536,-1
10,10,Scientists have discovered new evidence that t...,23.127678,-0.746845,0.399093,-4.260396,-104.567345,0

In [10]:
X = df[['e1', 'e2', 'e3', 'e4', 'e5']].values
y = df['target'].values

In [11]:
lp_model = LabelSpreading(kernel='knn', n_neighbors=5)
lp_model.fit(X, y)

LabelSpreading(kernel='knn', n_neighbors=5)

In [12]:
predicted_labels = lp_model.transduction_

In [13]:
label_map = {0: 'space', 1: 'biology'}
df['article_type'] = [label_map[label] for label in predicted_labels]

In [14]:
df.head(11)

,id,article_text,e1,e2,e3,e4,e5,target,article_type
0,0,Spin me round: Conceptual image of the distant...,-22.158750,0.724839,0.288074,-4.338476,-78.955190,-1,space
1,1,Euclid mission releases its first images\nThe ...,-69.417400,35.862324,-0.087313,-4.319662,71.955670,0,space
2,2,"This colourful stripe of stars, gas, and dust ...",-19.161320,16.865223,0.275305,-4.339422,-95.052050,-1,space
3,3,Scientists say they are stunned after discover...,39.257393,-0.624030,-0.312458,-3.406152,15.344043,-1,biology
4,4,Just a few swabs from a handful of leaves can ...,77.716700,-10.334601,-0.358630,-3.616157,35.430443,1,biology
5,5,"Standing on the marina, Rob Skelly peers into ...",25.035158,38.126000,-0.535336,-3.778501,-75.229970,-1,space
6,6,The James Webb space telescope has detected wh...,21.771069,-16.705242,0.035637,-4.280477,135.175920,-1,biology
7,7,We all know how important sleep is for mental ...,31.504581,37.482710,0.424354,-3.447748,-138.741090,1,biology
8,8,"In a former gold mine a mile underground, insi...",-6.323969,-16.945358,-0.056686,-4.229829,112.954500,-1,biology
9,9,Molecular scale structure and kinetics of laye...,34.213360,35.360607,0.041953,-3.384598,-7.783536,-1,biology
10,10,Scientists have discovered new evidence that t...,23.127678,-0.746845,0.399093,-4.260396,-104.567345,0,space

In [15]:
df.to_csv('text_embs_labeled.csv', index=False)